spring.application.name=demo3
# Configuration H2
spring.datasource.url=jdbc:h2:file:./data/blogdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console H2 (pour voir la base de données dans le navigateur)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console